### ISSUE TITLE
Возникает ошибка при подтверждении успешного оформления заказа

### ISSUE THREAD

**Issue by TemaMix** [ssnikolay/payanyway#12]
Сервис Payanyway, после проведения транзакции отправляет пользователя поэтому url:
/payanyway/success?MNT_TRANSACTION_ID

При этом осуществляется POST запрос, а в роутах гема используется GET, возникает ошибка RoutingError.

**Comment by ssnikolay** [comment]
В настройках счета **moneta.ru** выберите `HTTP метод: GET`

![Settings](https://raw.github.com/ssnikolay/payanyway/master/settings.jpg)

**Comment by TemaMix** [comment]
Метод GET выбран

**Comment by TemaMix** [comment]
Оказывается эта проблема решается, через тех. поддержку, нужно их попросить, чтобы ответ на success GET

**Comment by ssnikolay** [comment]
Странно, что они игнорят настройки конфига.
