### ISSUE TITLE
Routing Error

### ISSUE THREAD

**Issue by postgred** [ssnikolay/payanyway#9]
После того, как платеж прошел успешно, мне выдает Routing Error.

    Rails.application.routes.draw do

      mount Payanyway::Engine => '/payanyway'
      devise_for :users, controllers: { registrations: "registrations" }
      ....
    end

> rake route

    Routes for Payanyway::Engine
    payanyway_on_success_path	GET	/success(.:format)	payanyway#success
    payanyway_pay_path	GET	/pay(.:format)	payanyway#pay
    payanyway_on_fail_path	GET	/fail(.:format)	payanyway#fail
    payanyway_on_return_path	GET	/return(.:format)	payanyway#return
    payanyway_in_progress_path	GET	/in_progress(.:format)	payanyway#in_progress
    payanyway_on_check_path	GET	/check(.:format)	payanyway#check

При том что `payanyway_engine_path		/payanyway	Payanyway::Engine` доступен

Как решит эту проблему и где искать ошибку?

**Comment by ssnikolay** [comment]
postgred, привет! Что пишет в логах сервера при ошибке? Куда пытается стучаться?
Скорее всего у тебя в настройках аккаунта moneta.ru стоят некорректные пути "возврата".
Добавил расширенный скриншот настроек аккаунта https://github.com/ssnikolay/payanyway/pull/10/files

**Comment by postgred** [comment]
Да, ты прав. Спасибо за пример) На днях постараюсь прислать правки к README, объясняющие те некоторые мало понятные места для человека, которы

**Comment by ssnikolay** [comment]
Буду только рад, ибо у moneta.ru и правда не самое тривиальное юзабилити :)
